version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    - "8081:8081"
    - "8082:8082"
    volumes:
    - "/var/log/sales-booster-java-app:/var/log/sales-booster-java-app"
    environment:
      - "JAVA_OPTS=-Dserver.port=8080"