server:
  port: 8443
  ssl:
    key-store: certs/keystore.p12
    key-store-password: sbgce123
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  output:
    ansi:
#      colored console output
      enabled: always


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
  file:
    path: /var/log/sales-booster-java-app
    name: app.log
