server:
  port: 8081

spring:
  output:
    ansi:
#      colored console output
      enabled: always


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
  file:
    path: /var/log/sales-booster-java-app
    name: app.log
