name: remote ssh command
on:
  push:
    branches:
      - deploy
jobs:

  build:
    name: start app container
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deployment
            docker-compose up -d app