name: Deploy
on:
  release:
    types:
      - released
  push:
    branches:
      - deploy

jobs:
  build-deploy:

    env:
      PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
      GCE_INSTANCE: sales-booster
      GCE_INSTANCE_ZONE: europe-west4-a

    runs-on: ubuntu-latest

    steps:
      - name: setup env vars
        run: echo "::set-env name=REF::${GITHUB_REF#refs/tags/}"
      - uses: actions/checkout@v2

      - name: maven cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build no test
        run: mvn -B package -DskipTests


      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Build image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$REF" .

      - name: Publish image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$REF"

      - name: Update docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./docker-compose.yml"
          target: "~/deployment/"

      - name: Start application
        uses: appleboy/ssh-action@master
        envs: PROJECT_ID,GCE_INSTANCE,REF
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deployment
            export "IMAGE=gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$REF"
            docker-compose up --no-build -d app