name: remote ssh command
on:
  push:
    branches:
      - deploy
jobs:

  build:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: docker image list