name: test
on:
  push:
    branches: [ dev ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: setup env vars
        run: echo "${{ github.event.push.ref }}"

      - name: setup env vars
        run: echo "${{ github.event.release }}"